spring.application.name=user-service

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog.xml
spring.liquibase.default-schema=userservice

spring.jpa.database=postgresql
spring.jpa.show-sql=true

spring.cache.type=redis

spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE