spring.application.name=user-service

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog.xml
spring.liquibase.default-schema=userservice

spring.datasource.url=${DB_DATASOURCE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.jpa.database=postgresql
spring.jpa.show-sql=true